services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      # ホットリロードのためにソースコードをマウント
      - ./app/jobmatch-frontend:/app
      - /app/node_modules
    command: yarn run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true